### ISSUE TITLE
Two errors to run the docker

### ISSUE THREAD

**Issue by threefoldo** [tiagoarasilva/django-boilerplate#4]
1, 'channels' is not installed;
2, foundation6 is missing;

**Comment by tarsil** [comment]
Hi,

Thank you for your observation @threefoldo . Actually, I need to update the README about Foundation as the template locations can actually be chosen by the user who is installing the app. Can be foundation or any other html. About channels, Docker usually installs everything you need when you type docker-compose up but I will have a look and come back to you.

Thank you for your contribution on this.

**Comment by tarsil** [comment]
@threefoldo the system is now fixed and the templates are now placed with the README up-to-date.

Thank you for your contribution on this. I will close the ticket now, please let me know if something comes up.


Best,
Tiago
